/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TheFined (https://sketchfab.com/TheFined)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/floating-sky-island-b341e77708c54b5386005b41b1fe22fb
Title: Floating sky island
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import floatIslandScene from '../assets/3D/floating_sky_island.glb'

const floatingIsland = (props) => {
    const { nodes, materials } = useGLTF(floatIslandScene)
    return (
        <group {...props}>
            <mesh
                
                
                geometry={nodes['Icosphere002_Ground&Mountain_Texture_0'].geometry}
                material={materials.GroundMountain_Texture}
                position={[-36.259, 225.288, 255.97]}
                rotation={[-Math.PI / 2, 0, -0.49]}
                scale={28.918}
            />
            <mesh
                
                
                geometry={nodes.Cylinder002_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-61.889, 229.518, 231.084]}
                rotation={[-1.555, 0.024, -1.493]}
                scale={1.369}
            />
            <mesh
                
                
                geometry={nodes.Cylinder004_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-55.469, 223.754, 303.523]}
                rotation={[-1.562, -0.021, -0.504]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder005_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-2.404, 229.3, 197.999]}
                rotation={[-1.661, -0.009, 1.051]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder007_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-116.155, 223.732, 282.219]}
                rotation={[-1.562, -0.021, -0.504]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder008_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-55.856, 224.631, 132.6]}
                rotation={[-1.562, -0.021, -0.504]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder009_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-138.753, 223.174, 280.979]}
                rotation={[-1.584, -0.019, -1.521]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Icosphere007_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-57.702, 228.151, 291.432]}
                rotation={[-1.524, -0.047, -0.527]}
                scale={3.33}
            />
            <mesh
                
                
                geometry={nodes.Icosphere008_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-53.168, 232.326, 220.139]}
                rotation={[-1.41, -0.091, -0.944]}
                scale={3.897}
            />
            <mesh
                
                
                geometry={nodes.Icosphere010_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-131.509, 225.446, 266.196]}
                rotation={[-Math.PI / 2, 0, -2.032]}
                scale={1.77}
            />
            <mesh
                
                
                geometry={nodes.Icosphere011_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-3.259, 231.516, 203.572]}
                rotation={[-1.66, 0.058, 0.022]}
                scale={4.78}
            />
            <mesh
                
                
                geometry={nodes.Cylinder001_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-69.311, 225.398, 148.707]}
                rotation={[-1.551, 0.012, 1.222]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder006_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-72.194, 224.735, 135.091]}
                rotation={[-1.562, -0.021, -0.504]}
                scale={1.191}
            />
            <mesh
                
                
                geometry={nodes.Cylinder010_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-24.147, 230.745, 199.776]}
                rotation={[-1.601, -0.154, -0.503]}
                scale={1.191}
            />
            <mesh
                
                
                geometry={nodes.Cylinder011_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-91.613, 223.732, 336.19]}
                rotation={[-1.562, -0.021, -0.504]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-153.958, 224.356, 298.105]}
                rotation={[-Math.PI / 2, 0, -0.49]}
                scale={1.956}
            />
            <mesh
                
                
                geometry={nodes.Cylinder012_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-175.65, 223.45, 254.317]}
                rotation={[-Math.PI / 2, 0, -2.462]}
                scale={1.956}
            />
            <mesh
                
                
                geometry={nodes.Cylinder013_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-111.919, 221.174, 156.979]}
                rotation={[-Math.PI / 2, 0, 1.947]}
                scale={1.956}
            />
            <mesh
                
                
                geometry={nodes.Cylinder014_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-109.207, 228.261, 215.591]}
                rotation={[-1.531, 0.004, -0.215]}
                scale={2.023}
            />
            <mesh
                
                
                geometry={nodes.Icosphere003_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-78.237, 227.109, 150.35]}
                rotation={[-Math.PI / 2, 0, 2.559]}
                scale={4.78}
            />
            <mesh
                
                
                geometry={nodes.Icosphere005_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-100.027, 226.792, 152.329]}
                rotation={[-1.598, -0.092, 2.545]}
                scale={4.78}
            />
            <mesh
                
                
                geometry={nodes.Icosphere006_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-128.546, 226.792, 326.423]}
                rotation={[-1.602, 0.091, 0.019]}
                scale={6.694}
            />
            <mesh
                
                
                geometry={nodes.Icosphere012_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-117.064, 226.217, 233.223]}
                rotation={[-1.563, 0.004, -0.635]}
                scale={4.472}
            />
            <mesh
                
                
                geometry={nodes.Icosphere013_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-124.209, 225.981, 227.624]}
                rotation={[-Math.PI / 2, 0, -1.441]}
                scale={2.89}
            />
            <mesh
                
                
                geometry={nodes.Icosphere014_Rock_Texture_0.geometry}
                material={materials.Rock_Texture}
                position={[-119.828, 226.217, 227.672]}
                rotation={[-1.562, 0, -1.05]}
                scale={3.243}
            />
            <mesh
                
                
                geometry={nodes.Cylinder016_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-0.334, 227.554, 146.079]}
                rotation={[-1.539, -0.085, 2.883]}
                scale={1.684}
            />
            <mesh
                
                
                geometry={nodes.Cylinder017_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-72.733, 226.396, 190.515]}
                rotation={[-Math.PI / 2, 0, -0.641]}
                scale={1.956}
            />
            <mesh
                
                
                geometry={nodes.Cylinder015_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[-72.646, 227.764, 243.866]}
                rotation={[-1.543, 0.005, -2.322]}
                scale={1.75}
            />
            <mesh
                
                
                geometry={nodes.Cylinder003_Tree_Material_0.geometry}
                material={materials.Tree_Material}
                position={[23.446, 228.997, 193.924]}
                rotation={[-1.553, -0.054, -1.057]}
                scale={1.976}
            />
            <mesh
                
                
                geometry={nodes['Icosphere001_Ground&Mountain_Texture_0'].geometry}
                material={materials.GroundMountain_Texture}
                position={[-36.259, 225.288, 255.97]}
                rotation={[-Math.PI / 2, 0, -0.49]}
                scale={28.918}
            />
            <mesh
                
                
                geometry={nodes.Icosphere015_House_Texture_0.geometry}
                material={materials.House_Texture}
                position={[-99.007, 253.196, 248.229]}
                rotation={[-1.553, -0.015, -0.964]}
                scale={1.442}
            />
        </group>
    )
}

useGLTF.preload('/floating_sky_island.glb')

export default floatingIsland