/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marko Prokopyev (https://sketchfab.com/MarkoProkopyev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-circus-af59cbba6a3249bfb619e1b829964bd7
Title: Flying Circus
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3D/plane.glb'


const Plane = (props) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        actions["Dynamic pose"].play();
    }, []);
    
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="941b2da95bd54e61b701f8902ef2ed20fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="plane_body"
                                    position={[-318.813, 331.087, -1.721]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}>
                                    <mesh
                                        name="plane_body_M_plane_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.plane_body_M_plane_0.geometry}
                                        material={materials.M_plane}
                                    />
                                    <group name="outline" position={[3.188, -0.017, -0.714]} rotation={[0, 1.571, 0]}>
                                        <mesh
                                            name="outline_M_outline_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.outline_M_outline_0.geometry}
                                            material={materials.M_outline}
                                        />
                                    </group>
                                    <group name="aileron_left" position={[4.632, -3.457, -1.167]}>
                                        <mesh
                                            name="aileron_left_M_plane_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.aileron_left_M_plane_0.geometry}
                                            material={materials.M_plane}
                                        />
                                        <group
                                            name="outline001"
                                            position={[-1.444, 3.44, 0.453]}
                                            rotation={[0, 1.571, 0]}>
                                            <mesh
                                                name="outline001_M_outline_0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.outline001_M_outline_0.geometry}
                                                material={materials.M_outline}
                                            />
                                        </group>
                                    </group>
                                    <group name="aileron_right" position={[4.39, 3.103, -1.195]}>
                                        <mesh
                                            name="aileron_right_M_plane_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.aileron_right_M_plane_0.geometry}
                                            material={materials.M_plane}
                                        />
                                        <group
                                            name="outline002"
                                            position={[-1.201, -3.121, 0.481]}
                                            rotation={[0, 1.571, 0]}>
                                            <mesh
                                                name="outline002_M_outline_0"
                                                castShadow
                                                receiveShadow
                                                geometry={nodes.outline002_M_outline_0.geometry}
                                                material={materials.M_outline}
                                            />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature"
                                        position={[8.423, -0.033, -0.113]}
                                        rotation={[0, 1.571, 0]}>
                                        <group name="Object_17">
                                            <primitive object={nodes._rootJoint} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature001"
                                        position={[8.435, -0.035, 1.451]}
                                        rotation={[0, 0, 0.036]}>
                                        <group name="Object_28">
                                            <primitive object={nodes._rootJoint_1} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature003"
                                        position={[1.985, 0.988, -0.515]}
                                        rotation={[-2.128, 0.387, -0.026]}>
                                        <group name="Object_37">
                                            <primitive object={nodes._rootJoint_2} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature004"
                                        position={[1.985, 0.76, -0.848]}
                                        rotation={[-2.256, 0.387, 0.022]}>
                                        <group name="Object_46">
                                            <primitive object={nodes._rootJoint_3} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature002"
                                        position={[1.985, -0.984, -0.515]}
                                        rotation={[-1.014, -0.387, 3.115]}
                                        scale={-1}>
                                        <group name="Object_55">
                                            <primitive object={nodes._rootJoint_4} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature005"
                                        position={[1.985, -0.834, -0.848]}
                                        rotation={[-0.882, -0.387, -3.118]}
                                        scale={-1}>
                                        <group name="Object_64">
                                            <primitive object={nodes._rootJoint_5} />
                                        </group>
                                    </group>
                                    <group
                                        name="Armature006"
                                        position={[3.762, -4.705, -0.751]}
                                        rotation={[0, -0.08, 0]}>
                                        <group name="Object_73">
                                            <primitive object={nodes._rootJoint_6} />
                                        </group>
                                    </group>
                                    <group name="smoke" position={[2.672, -1.534, -0.855]} scale={0}>
                                        <mesh
                                            name="smoke_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group name="smoke001" position={[2.672, -1.534, -0.855]} scale={0}>
                                        <mesh
                                            name="smoke001_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke001_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke002"
                                        position={[2.828, -1.522, -0.4]}
                                        rotation={[0.837, 0.145, -1.506]}
                                        scale={0.948}>
                                        <mesh
                                            name="smoke002_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke002_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke003"
                                        position={[7.577, -1.534, -0.74]}
                                        rotation={[0.722, 0.18, -1.938]}
                                        scale={1.283}>
                                        <mesh
                                            name="smoke003_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke003_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke004"
                                        position={[6.893, -1.534, -0.669]}
                                        rotation={[0.604, -0.261, 1.625]}
                                        scale={0.384}>
                                        <mesh
                                            name="smoke004_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke004_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke005"
                                        position={[7.838, -1.534, -0.847]}
                                        rotation={[0.883, -0.438, 1.291]}
                                        scale={0.016}>
                                        <mesh
                                            name="smoke005_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke005_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke006"
                                        position={[7.577, 1.286, -0.74]}
                                        rotation={[-0.723, -0.175, 1.197]}
                                        scale={1.283}>
                                        <mesh
                                            name="smoke006_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke006_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group name="smoke007" position={[2.672, 1.286, -0.855]} scale={0}>
                                        <mesh
                                            name="smoke007_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke007_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group name="smoke008" position={[2.672, 1.286, -0.855]} scale={0}>
                                        <mesh
                                            name="smoke008_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke008_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke009"
                                        position={[2.828, 1.298, -0.4]}
                                        rotation={[-0.837, -0.145, 1.636]}
                                        scale={0.948}>
                                        <mesh
                                            name="smoke009_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke009_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke010"
                                        position={[6.893, 1.286, -0.669]}
                                        rotation={[-0.604, 0.261, -1.517]}
                                        scale={0.384}>
                                        <mesh
                                            name="smoke010_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke010_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="smoke011"
                                        position={[7.838, 1.286, -0.847]}
                                        rotation={[-0.883, 0.438, -1.85]}
                                        scale={0.016}>
                                        <mesh
                                            name="smoke011_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.smoke011_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                </group>
                                <group
                                    name="propeller"
                                    position={[-318.813, 331.087, -1.721]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}>
                                    <mesh
                                        name="propeller_M_plane_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.propeller_M_plane_0.geometry}
                                        material={materials.M_plane}
                                    />
                                    <group
                                        name="fx"
                                        position={[0.096, -0.007, 0.002]}
                                        rotation={[0, Math.PI / 2, 0]}
                                        scale={2.27}>
                                        <mesh
                                            name="fx_M_vfx_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.fx_M_vfx_0.geometry}
                                            material={materials.M_vfx}
                                        />
                                    </group>
                                    <group
                                        name="outline005"
                                        position={[3.188, -0.017, -0.714]}
                                        rotation={[0, 1.571, 0]}>
                                        <mesh
                                            name="outline005_M_outline_0"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.outline005_M_outline_0.geometry}
                                            material={materials.M_outline}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}
//useGLTF.preload('/flying_circus.glb')
export default Plane